#!/usr/bin/env ruby

# Optional filename to which to write the install script
name = ARGV.shift.to_s.strip

if !File.directory?("scripts")
   puts "** ERROR: Run script from the schema directory of your project"
   exit(1)
end

def assert_installed(cmd, url)
  if !system("which %s > /dev/null" % cmd)
    puts "** ERROR: Please install %s: %s" % [cmd, url]
    exit(1)
  end
end

def format(path)
  path.sub(/.*lib-postgresql\//, 'https://github.com/flowcommerce/lib-postgresql/blob/master/')
end

def different?(updated, original)
  if !File.exists?(updated)
    true
  elsif !File.exists?(original)
    true
  else
    IO.read(updated).strip != IO.read(original).strip
  end
end
  
def run_command(cmd)
  puts cmd
  if !system(cmd)
    puts "** ERROR: command failed"
    exit(1)
  end
  puts "Example commit:"
  puts " git commit -m 'Installed lib-postgresql scripts' scripts"
end

assert_installed("sem-add", "https://github.com/mbryzek/schema-evolution-manager")

dir = File.dirname(__FILE__)
tmp = "lib-postgresql-schema-tmp.sql"

begin
  File.open(tmp, "w") do |out|
    out << "-- File created automatically by #{format(__FILE__)}\n\n"
  
    Dir.glob("#{dir}/*.sql").sort.each do |path|
      out << "\n-- Start of file #{format(path)}\n"
      out << IO.read(path)
    end
  end

  if name == ""
    run_command("sem-add #{tmp}")
  elsif different?(tmp, name)
    run_command("cp #{tmp} #{name}")
  else
    puts "No changes compared to #{name}"
  end
ensure
  if File.exists?(tmp)
    File.delete(tmp)
  end
end
